// tests/mixpanel/tracking.spec.ts
// Auto-generated by Mixpanel GitHub App — do not edit manually.
import { test, expect } from "@playwright/test";
import type { Page } from "@playwright/test";

interface MixpanelEvent {
  event: string;
  properties?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Helper: intercept Mixpanel network requests and collect events
// ---------------------------------------------------------------------------
function setupMixpanelInterceptor(page: Page): MixpanelEvent[] {
  const captured: MixpanelEvent[] = [];

  /**
   * Decode a Mixpanel request body.
   * GET requests use ?data=<base64url-encoded JSON array>
   * POST requests send the payload as form-encoded "data" field.
   */
  async function parseEvents(
    route: Parameters<Parameters<Page["route"]>[1]>[0]
  ): Promise<void> {
    const request = route.request();
    let raw = "";

    if (request.method() === "POST") {
      const body = request.postData() ?? "";
      // "data=<base64>" or raw JSON array
      const match = body.match(/(?:^|&)data=([^&]+)/);
      raw = match ? decodeURIComponent(match[1]) : body;
    } else {
      const url = new URL(request.url());
      raw = url.searchParams.get("data") ?? "[]";
    }

    try {
      const decoded = Buffer.from(raw, "base64").toString("utf-8");
      const batch: MixpanelEvent[] = JSON.parse(decoded);
      captured.push(...batch);
    } catch {
      // Not base64 — try plain JSON
      try {
        const batch: MixpanelEvent[] = JSON.parse(raw);
        captured.push(...batch);
      } catch {
        // Malformed payload; ignore
      }
    }

    // Fulfill immediately so Mixpanel doesn't retry
    await route.fulfill({ status: 200, body: "1" });
  }

  // Intercept both the legacy GET endpoint and the modern POST endpoint
  page.route("**/api-js.mixpanel.com/**", parseEvents);
  page.route("**/api.mixpanel.com/track**", parseEvents);

  return captured;
}

// ---------------------------------------------------------------------------
// Per-event tests
// ---------------------------------------------------------------------------
test("fires team_member_invited on Invite form submitted successfully", async ({ page }) => {
  const events = setupMixpanelInterceptor(page);
  await page.goto("/dashboard");
  await page.click("form[action*='inviteTeamMember']");
  await page.waitForTimeout(500);
  const found = events.find((e) => e.event === "team_member_invited");
  expect(found).toBeTruthy();
  expect(found?.properties?.member_role).toBeDefined();
  expect(found?.properties?.team_size).toBeDefined();
});

test("fires subscription_started on Stripe checkout session completed", async ({ page }) => {
  const events = setupMixpanelInterceptor(page);
  await page.goto("/pricing");
  await page.click("form[action*='checkoutAction']");
  await page.waitForTimeout(500);
  const found = events.find((e) => e.event === "subscription_started");
  expect(found).toBeTruthy();
  expect(found?.properties?.plan_name).toBeDefined();
  expect(found?.properties?.price_amount).toBeDefined();
});

test("fires settings_updated on Settings form saved successfully", async ({ page }) => {
  const events = setupMixpanelInterceptor(page);
  await page.goto("/dashboard/general");
  await page.click("form[action*='updateAccount'], form[action*='updatePassword']");
  await page.waitForTimeout(500);
  const found = events.find((e) => e.event === "settings_updated");
  expect(found).toBeTruthy();
  expect(found?.properties?.setting_type).toBeDefined();
  expect(found?.properties?.user_role).toBeDefined();
});

test("fires dashboard_viewed on Dashboard page load", async ({ page }) => {
  const events = setupMixpanelInterceptor(page);
  await page.goto("/dashboard");
  // Page-view event — no interaction needed
  await page.waitForTimeout(500);
  const found = events.find((e) => e.event === "dashboard_viewed");
  expect(found).toBeTruthy();
  expect(found?.properties?.has_subscription).toBeDefined();
  expect(found?.properties?.team_members_count).toBeDefined();
});
